using System.Collections.Generic;
using Newtonsoft.Json;
using SoobakFigma2Unity.Editor.Models;

namespace SoobakFigma2Unity.Editor.Import
{
    /// <summary>
    /// Data model for the .soobak.json export file generated by the Figma Plugin.
    /// </summary>
    [System.Serializable]
    internal sealed class SoobakExportFile
    {
        [JsonProperty("manifest")] public ExportManifest Manifest;
        [JsonProperty("embeddedImages")] public Dictionary<string, string> EmbeddedImages;
    }

    [System.Serializable]
    internal sealed class ExportManifest
    {
        [JsonProperty("version")] public string Version;
        [JsonProperty("exportedAt")] public string ExportedAt;
        [JsonProperty("fileName")] public string FileName;
        [JsonProperty("fileKey")] public string FileKey;
        [JsonProperty("imageScale")] public float ImageScale = 2f;
        [JsonProperty("frames")] public List<FigmaNode> Frames;
        [JsonProperty("components")] public Dictionary<string, FigmaComponent> Components;
        [JsonProperty("componentSets")] public Dictionary<string, FigmaComponentSet> ComponentSets;
        [JsonProperty("images")] public Dictionary<string, string> Images;
        [JsonProperty("imageFills")] public Dictionary<string, string> ImageFills;
    }
}
