using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using SoobakFigma2Unity.Editor.Models;
using SoobakFigma2Unity.Editor.Pipeline;
using SoobakFigma2Unity.Editor.Util;
using UnityEngine;

namespace SoobakFigma2Unity.Editor.Import
{
    /// <summary>
    /// Loads a .soobak.json export file generated by the Figma Plugin.
    /// Extracts embedded images and populates the ImportContext.
    /// </summary>
    internal sealed class SoobakExportLoader
    {
        private readonly ImportLogger _logger;

        public SoobakExportLoader(ImportLogger logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Load and parse a .soobak.json file.
        /// </summary>
        public SoobakExportFile Load(string filePath)
        {
            if (!File.Exists(filePath))
            {
                _logger.Error($"File not found: {filePath}");
                return null;
            }

            _logger.Info($"Loading export: {Path.GetFileName(filePath)}...");

            try
            {
                var json = File.ReadAllText(filePath);
                var export = JsonConvert.DeserializeObject<SoobakExportFile>(json);

                if (export?.Manifest == null)
                {
                    _logger.Error("Invalid .soobak.json file: no manifest found.");
                    return null;
                }

                _logger.Success($"Loaded: {export.Manifest.FileName} ({export.Manifest.Frames?.Count ?? 0} frames, " +
                    $"{export.EmbeddedImages?.Count ?? 0} images)");

                return export;
            }
            catch (Exception e)
            {
                _logger.Error($"Failed to parse export file: {e.Message}");
                return null;
            }
        }

        /// <summary>
        /// Extract embedded base64 images to disk and populate ImportContext paths.
        /// </summary>
        public void ExtractImages(SoobakExportFile export, string imageOutputDir, ImportContext ctx)
        {
            if (export.EmbeddedImages == null || export.EmbeddedImages.Count == 0)
            {
                _logger.Info("No embedded images to extract.");
                return;
            }

            Directory.CreateDirectory(imageOutputDir);

            int count = 0;
            foreach (var kv in export.EmbeddedImages)
            {
                var relativePath = kv.Key;   // e.g. "images/0_1.png"
                var base64Data = kv.Value;

                try
                {
                    var bytes = Convert.FromBase64String(base64Data);
                    var fileName = Path.GetFileName(relativePath);
                    var outputPath = Path.Combine(imageOutputDir, fileName);
                    File.WriteAllBytes(outputPath, bytes);

                    // Map back to node ID or fill ref
                    if (export.Manifest.Images != null)
                    {
                        foreach (var imgKv in export.Manifest.Images)
                        {
                            if (imgKv.Value == relativePath)
                            {
                                ctx.NodeImagePaths[imgKv.Key] = outputPath;
                                break;
                            }
                        }
                    }

                    if (export.Manifest.ImageFills != null)
                    {
                        foreach (var fillKv in export.Manifest.ImageFills)
                        {
                            if (fillKv.Value == relativePath)
                            {
                                ctx.FillImagePaths[fillKv.Key] = outputPath;
                                break;
                            }
                        }
                    }

                    count++;
                }
                catch (Exception e)
                {
                    _logger.Error($"Failed to extract image {relativePath}: {e.Message}");
                }
            }

            _logger.Success($"Extracted {count} images to {imageOutputDir}");
        }
    }
}
